M48
; DRILL file {KiCad 9.0.1} date 2025-12-04T23:43:19-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-12-04T23:43:19-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
%
G90
G05
T1
X4.9535Y-4.8425
X4.9535Y-5.0701
T2
X3.4524Y-3.9829
X3.6524Y-3.9429
X3.6524Y-4.0229
M30
